# Generated by Django 5.2.7 on 2025-10-03 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_manager', '0007_department_user_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_start', models.DateTimeField()),
                ('shift_end', models.DateTimeField()),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift_manager.user')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift_manager.user')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift_manager.shift')),
            ],
            options={
                'unique_together': {('user', 'shift')},
            },
        ),
    ]
