# Generated by Django 5.2.7 on 2025-10-12 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_manager', '0009_alter_shift_shift_end_alter_shift_shift_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shift_manager.shiftpattern'),
        ),
    ]
