# Generated by Django 5.2.7 on 2025-10-15 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_manager', '0010_shift_pattern'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='pattern',
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_assignments', to='shift_manager.user')),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift_manager.shiftpattern')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift_manager.user')),
            ],
            options={
                'unique_together': {('user', 'date', 'pattern')},
            },
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='Shift',
        ),
    ]
